training:
  lr: 5e-3
  batch_size: 256
  verbose: false
  seed: 17
  hist_record_num: 20
  train_ratio: 0.9
  print_freq: 300
  workers: 0
  start_epoch: 0
  epochs: 1500
  debug_mode: false
  model_stats_tracker: false
  checkpoint_folder: /data/Pein/Pytorch/Ascend-NPU-Parallel-Training/checkpoints
  checkpoint_path:
  ckpt_save_interval: 200

commit:
  commit_message: "res34-5e-3"
  commit_file_path: /data/Pein/Pytorch/Ascend-NPU-Parallel-Training/3-tb_logs/commit_log.csv

model:
  arch: resnet34
  pretrained: false

optimizer:
  name: SGD
  momentum: 0.9
  weight_decay: 5e-4
  betas: [0.9, 0.99]
  criterion: CrossEntropyLoss

scheduler:
  type: ReduceLROnPlateau
  mode: min
  factor: 0.5 # for lr reduction
  patience: 75
  warmup_iters: 0

early_stopping:
  delta: 1e-4
  patience: 150

data:
  path: /data/Pein/Pytorch/Ascend-NPU-Parallel-Training/cifar100_data
  dataset_name: cifar100
  dummy: false

logging:
  tb_log_dir: /data/Pein/Pytorch/Ascend-NPU-Parallel-Training/3-tb_logs/
  # checkpoint_folder: /data/Pein/Pytorch/Ascend-NPU-Parallel-Training/checkpoints
  # checkpoint_path:

evaluation:
  is_evaluation_enabled: true
  is_validation_enabled: true

distributed_training:
  distributed: true
  world_size: 1
  rank: 0
  dist_url: tcp://192.168.18.48:12345
  dist_backend: hccl
  master_addr: 192.168.18.48
  master_port: 12345
  multiprocessing_distributed: true
  gpu: None
  device: npu
  device_list: [0, 1, 2, 3, 4, 5, 6, 7]

amp:
  is_amp_enabled: false
  loss_scale: 1024.
  opt_level: O0
